name: gpu-test-base.yml
on:
  push:
    branches:
      - 'E-cypress-test-case'
  pull_request:
  workflow_dispatch:

jobs:
  base:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        browser: [electron, chrome, chromium, edge, firefox]
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Cypress run
        uses: cypress-io/github-action@v5
        with:
          browser: ${{ matrix.browser }}
